### PR TITLE
User crontab to correctly set up cron.

### PR DESCRIPTION
**Pull request by mramato**
@omh1280 while I couldn't figure out the cron issue for non-root users (we'll just run root for now), I did find a bunch of issues with how you were setting up cron and made the following changes:

1. Rather than trying to set things up manually, use crontab to import the existing cron file as documented in the man page.
2. supervisord was running cron incorrectly, needed `-l` not `-L`.
3. Redirect all supervisord task output to stdout and stderr
4. Specify the supervisord configuration file directly rather than relying on putting it in `/etc`.
5. Remove unnecessary `root` specification in crontab.

Can you please test and merge.

Also, it looks like you have the task set up to run every minute, obviously that's far too often.  I assume once a day is probably enough.  Please make this change upstream after you review/test/merge this.

Thanks.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
@mramato thanks for the pull request!

I noticed that [`CHANGES.md`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the Cesium API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and bump this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by cesium-concierge** [comment]
Thank you for the pull request!

Looks like this pull request hasn't been updated in 0 days since I last commented.
To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?

__I am a bot who helps facilitate your development!__ Have a nice day.

**Comment by omh1280** [comment]
@mramato Looks good! It works on my machine, after a quick fix that I just committed.

Why is the logging level `info`? Don't we want a lot of logging to see what went wrong? Also, the `-L` is supposed to be capital, at least according to [this](https://gist.github.com/martinrusev/7015e393d46647dbad15#gistcomment-1850620)

**Comment by mramato** [comment]
> Why is the logging level info? Don't we want a lot of logging to see what went wrong?

`debug` logging level is just that, meant for debugging.  In normal production mode you wouldn't want that level of info because it generates too much noise.  It's all about finding the right balance.

> Also, the -L is supposed to be capital, at least according to this

Thanks, I swear I saw another man page that has something different, I'll push a fix.  I verified you're correct by looking at the actual man page for cron in our Docker instance.

**Comment by mramato** [comment]
This should be ready.

**Comment by omh1280** [comment]
Ok, sounds good.

Yeah I think there's different versions of Cron. I've seen completely different options as well.

Thanks!

**Comment by mramato** [comment]
FYI, we generally delete branches after merging, so don't forget to his `Delete branch` after you merge someone's PR.

**Pull request merged**
