### PR TITLE
Only report last week's PRs in weekly stats

### PR DESCRIPTION
**Pull request by OmarShehata**
This fixes https://github.com/AnalyticalGraphicsInc/cesium-concierge/issues/135 and adds a test to ensure that it works.

Slackbot will currently report that a PR was merged last week even if it was merged a long time ago, but someone commented on it last week. The other problem is getting a list of pull requests doesn't differentiate `merged` from `closed`. In order to check if a `PR` is merged or not we need to make another API request. This complicated the code a bit so I refactored it should be a lot simpler now. 

While working on this I also noticed the way we were authenticating with GitHub using the OctokitJS libary was deprecated so I updated that as well. 

Coverage is still high at ~95% and all new code is 100% covered. 

TODO: 

* [ ] Do the same check for before commenting on a closed PR to make sure it's been merged instead of just closed.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @OmarShehata! 
* :heavy_check_mark: Signed CLA found. 
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium-concierge/blob/filter-issues/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by OmarShehata** [comment]
@ggetz

**Comment by OmarShehata** [comment]
@ggetz actually let me see if I can also filter out prs that were closed instead of merged and I'll ping you again

**Comment by OmarShehata** [comment]
I've fixed the issue with it reporting PRs that were closed instead of merged. I've updated the PR description @ggetz .

**Comment by OmarShehata** [comment]
@ggetz this should be good to merge.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by OmarShehata** [comment]
Oh no, please don't close this @cesium-concierge !  It's for your own good.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by OmarShehata** [comment]
I've opted to remove the check for first time contributors. There's no straightforward way that I can see to check for this once the PR is merged without some kind of database I can write to when the PR is first opened.

When you merge a PR and get the webhook, you can't check the branch they're merging into for `CONTRIBUTORS.md` because the webhook runs after the PR is merged, so their name will already be in there. You could try to go through the history of the contributors file to see if it was there at the time the PR was opened, but it seemed too much to orchestrate here so I punted on it for now.

**Pull request merged**
